### PR TITLE
dont catch errors thrown in callbacks

### LINKED ISSUE #62: Don't catch errors thrown in callbacks
Currently oboe catches errors thrown in callbacks and triggers the fail event
```javascript
/** 
*  wrap a callback so that if it throws, Oboe.js doesn't crash but instead
*  handles it like a normal error
*/
function protectedCallback( callback ) {
  return function() {
    try {      
      return callback.apply(oboeApi, arguments);   
    } catch(e)  {

      // An error occured during the callback, publish it on the event bus 
      oboeBus(FAIL_EVENT).emit( errorReport(undefined, undefined, e));
    }      
  }   
}
```
I agree that oboe.js should not crash if there is an error thrown in a callback. However, I disagree that the error should be caught and passed to the fail event handler. Firstly, catching errors in functions it receives as arguments should not be a responsibility of oboe. Secondly, the fail event handler should just be for unsuccessful requests

Thus I suggest the code be updated to the following:
```javascript
/** 
*  execute the callback in its own event loop so that if it throws, Oboe.js doesn't crash
*/
function protectedCallback( callback ) {
  return function() {
    setTimeout(callback.bind(oboeApi, arguments));     
  }   
}
```
This way errors in callbacks do not cause oboe to crash and errors thrown by callbacks are not caught.

I am happy to implement this change, but want to get feedback before I spend time updating the tests.

### PR DESCRIPTION
**Pull request by charlierudolph**
resolves #62 

Add `?w=1` when inspecting the files to ignore whitespace.

### CODE REVIEW

**Comment by JuanCaicedo** [comment]
Hey @charlierudolph, thanks for the PR, especially for updating the tests with it ! I'll look through it and add as much info as possible, then I'll tag @jimhigson to come take a look.

If I check out your branch and run `npm test`, I get a few failing tests. These pass for me on master. Does this pass for you? Travis is seeing the same thing as me if you want to investigate.

**Comment by charlierudolph** [comment]
Those were some tests I missed. I'll update them,

**Comment by charlierudolph** [comment]
@JuanCaicedo got everything passing. I ended up updating `dist` as part of the running the tests. Please let me know if those changes need to be reverted

**Comment by JuanCaicedo** [comment]
As far as `dist` I'm actually not really sure, I'll let Jim make the call. 

PR looks good to me!

**Comment by charlierudolph** [comment]
@jimhigson @JuanCaicedo any updates?

**Comment by JuanCaicedo** [comment]
@charlierudolph just wanted to say thanks again for your PR! I haven't been heard back from Jim when I last contacted him about open PRs and don't know how he feels about me merging things to master without his review. Sorry for the delay

**Comment by JuanCaicedo** [comment]
@charlierudolph Sorry again that this has taken so long, I guess Jim hasn't had time to get to it. My thought right now is to merge PRs into another branch called `dev` and then go ahead and make a PR from there to master for a new release. 

Hope that sounds good to you! I can go ahead and change the base branch myself, so I'll do that and merge.

**Pull request merged**
