### PR TITLE
Fixed scientific notation across chunks bug

### PR DESCRIPTION
**Pull request by mwlon**
If chunks were `... 1.2e`, `+17, ...`, then previous p would be set to '+' upon reaching the 2nd chunk, causing an invalid symbol error since both p and c were '+'.

### CODE REVIEW

**Comment by JuanCaicedo** [comment]
Thanks for this fix! Unfortunately dist is a build artifact, so any changes to it will be overwritten the next time we build a release. It probably shouldn't be committed to source control.

Your change probably needs to be applied here https://github.com/jimhigson/oboe.js/blob/master/src/libs/clarinet.js#L169

Note that Oboe uses a committed (and out of date) version of [Clarinet](https://github.com/dscape/clarinet). It also doesn't seem very maintained, but I would flag this issue for them in case they're interested in fixing it there as well 😃

**Comment by mwlon** [comment]
Ah, duh. So I updated it in the right place, but now I'm getting what seems to be an unrelated error: `SyntaxError: Use of const in strict mode.` Do you know what that's about?

**Comment by JuanCaicedo** [comment]
Hmm, not sure, could you push a branch up to your fork with it?

**Comment by mwlon** [comment]
Did you find anything?

**Comment by JuanCaicedo** [comment]
Yeah, the problem seems to be coming from a sub dependency of `request`, which looks to use ES6 syntax, which the build doesn't support
> /home/travis/build/jimhigson/oboe.js/node_modules/request/node_modules/hawk/lib/index.js:5:33

I think that what probably happened is that `request` does not specify its dependencies strictly enough, so npm is installing a newer version of hawk. Solutions could include:

- Use npm-lock
- Use npm 5 which locks by default
- Use yarn which locks by default

None of these are problems with your branch, however this work will have to be done before this branch can be merged. I can try to do it when I have time or if any of you want to take it on @mwlon, @ehlemur, @sergiobonfiglio, I'm glad to play backup 😃

**Comment by mwlon** [comment]
It's not a general fix like locking the dependencies, but I fixed the `request` version, which solves the problem in this case. Good to merge?

**Comment by mwlon** [comment]
@JuanCaicedo Can we merge this?

**Comment by JuanCaicedo** [comment]
@mwlon Yeah this looks good to me! Thanks

**Comment by JuanCaicedo** [comment]
Released in https://github.com/jimhigson/oboe.js/releases/tag/v2.1.4

**Pull request merged**
