### PR TITLE
Added web worker support

### PR DESCRIPTION
**Pull request by ScreenDriver**
See issue #58

### CODE REVIEW

**Comment by jimhigson** [comment]
oboe.browser.js is the concatenated version of the file that gets built via gunt. I'll port this over to the src dir when I get a moment. Looks fine otherwise.

**Comment by jimhigson** [comment]
Sorry, somehow I misread that entirely. The right file got edited!

**Comment by jimhigson** [comment]
Edited slightly to avoid creating a new global but otherwise merged. Thanks.

**Comment by ScreenDriver** [comment]
:+1:

**Pull request merged**
