### PR TITLE
test(streamingHttp): show fail and done being called together

### LINKED ISSUE #64: .done and .fail are both called on error response with payload
When receiving an error response with a payload, oboe fires the `done` callback, followed by the `fail` callback.

This is the response I'm receiving:

```
HTTP/1.1 401 Unauthorized
Cache-Control: private
Transfer-Encoding: chunked
Content-Type: application/json; charset=utf-8
Date: Mon, 06 Apr 2015 09:13:01 GMT

{"code":1,"message":"Invalid credentials"}
```

The `done` method fires first and is passed the parsed JSON response object. The `fail` method fires shortly thereafter with the statusCode correctly set.

Unless I'm mistaken, `done` should not be fired here because the response contains an error. This is what happens when the webserver returns just an error code with no JSON response.

### PR DESCRIPTION
**Pull request by Aigeec**
fixes #64

Will be implementing the same fix as others provided before. Have written tests to demonstrate the bug. The fix will in the next push.

### CODE REVIEW

**Comment by Aigeec** [comment]
Sorry about all the reverts. I pushed the fix to early and the first travis run didn't fail as intended. Then I reverted the wrong one. All sorted now. If a little messy. Could squash this merge :)

**Comment by amit777** [comment]
Hi, is this fix planned to be merged into master and released? just got bit by the issue as well.

**Comment by Aigeec** [comment]
This was merged to master a year ago. What version are you using?

**Comment by amit777** [comment]
Ahh, sorry yes, I see that. I think there hasn’t been a release since then.
I’m using 2.1.4.

**Comment by Aigeec** [comment]
I think there was an alpha release.

@JuanCaicedo any reason not too do a full release?

**Pull request merged**
